name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps: 
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make payloads

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
          name: openra1n
          path: |
            ${{ github.workspace }}/
